### ISSUE TITLE
Métodos anônimos

### ISSUE THREAD

**Issue by marcianobandeira** [HashLoad/horse-jwt#11]
Boa tarde, como eu devo proceder para indicar ao horse que algum metodo é anônimo, não devendo portanto, passar pela midleware de validação do token jwt?

Grato

**Comment by viniciussanchez** [comment]
Boa tarde, da uma olhada nesse projeto aqui...
https://github.com/HashLoad/kanbana-api
mas basicamente você vai definir método por método qual que vai e qual nao vai ter a autenticação. Pode inclusive usar dois tipos de autenticação em um unico servidor, como mostra nesse exemplo

**Comment by marcianobandeira** [comment]
Opa, obrigado por responder tão rapidamente. show de bola, deu pra entender pelo seu projeto... fiz um exemplo nesse formato aqui e funcionou perfeitamente. obrigado.

Vou deixar aqui para alguam eventual consulta.

class function TProServerApp.Authenticated: THorseCallback;
const secret = 'fdafdas';
begin
  Result := HorseJWT(secret);
end;

class procedure TProServerApp.Start;
var app: THorse;
begin
  app := THorse.Create(9000);
  try
    // anonimo
    app.Get('/hello', TPessoaController.Get);
    // autenticado
    app.Get('/cliente', TProServerApp.Authenticated, TPessoaController.Get);
    app.Start;
  finally
    FreeAndNil(app);
  end;
end;
