### ISSUE TITLE
Session não funciona

### ISSUE THREAD

**Issue by williammattos** [HashLoad/horse-jwt#16]
A variável Session não recebe o conteúdo corretamente.

Acredito ser por conta da mudança do código da linha 163 do HorseJWT

```delphi
{...}
TJWTClaims(LSession).JSON := LJSON.Clone as TJSONObject;
{...}
```

**Comment by viniciussanchez** [comment]
O problema que você falou foi devido ao commit 35e5ec92373a3037151f9192bb7ab3b3aec552f7 feito pelo @dliocode.
Precisava verificar certinho, eu não uso esse recurso. Tem que ver o porque da mudança, e deixar funcionando para ambos...

**Comment by williammattos** [comment]
Eu não entendi muito bem, suponho que no caso dele a Session dele dever herdar de TJWTClaims ou TJOSEBase

**Comment by williammattos** [comment]
Vamos aguardar para poder manter no melhor nivel de compatibilidade,
se alguém estiver com o mesmo problema, um workaround no momento é herdar a session de TJWTClaims e acessar como abaixo.

```delphi
{...}
uses
  JOSE.Core.JWT
{...}
TMySession = class(TJWTClaims)
{...}
AReq.Session<TMySession>.JSON.GetValue('empresa').Value
{...}
```

**Comment by maicorheinheimer** [comment]
Atualizei e também me deparei com este problema que o colega @williammattos reportou. Fiz o indicado acima e funcionou para mim paliativamente .

**Comment by dliocode** [comment]
Olá pessoal, sobre o ocorrido,  quando se faz um JWTClaims personalizado, deve ser criado a class herdando o TJWTClaims.

Segue o exemplo de um Claim Personalizado:

```delphi
unit MyClaims;

interface

uses
  JOSE.Core.JWT, JOSE.Types.JSON;

type
  TMyClaims = class(TJWTClaims)
  strict private
    function GetEmail: string;
    function GetName: string;
    procedure SetEmail(const Value: string);
    procedure SetName(const Value: string);
    function GetId: string;
    procedure SetID(const Value: string);
  public
    property Id: string read GetId write SetID;
    property name: string read GetName write SetName;
    property Email: string read GetEmail write SetEmail;
  end;

implementation

{ TMyClaims }

function TMyClaims.GetEmail: string;
begin
  Result := TJSONUtils.GetJSONValue('email', FJSON).AsString;
end;

function TMyClaims.GetId: string;
begin
  Result := TJSONUtils.GetJSONValue('id', FJSON).AsString;
end;

function TMyClaims.GetName: string;
begin
  Result := TJSONUtils.GetJSONValue('name', FJSON).AsString;
end;

procedure TMyClaims.SetEmail(const Value: string);
begin
  TJSONUtils.SetJSONValueFrom<string>('email', Value, FJSON);
end;

procedure TMyClaims.SetID(const Value: string);
begin
  TJSONUtils.SetJSONValueFrom<string>('id', Value, FJSON);
end;

procedure TMyClaims.SetName(const Value: string);
begin
  TJSONUtils.SetJSONValueFrom<string>('name', Value, FJSON);
end;

end.
```

Como se usa e onde se usa?

* Se usa durante a criação do token e na leitura!
* No exemplo abaixo podemos ver TMyClaims sendo usado na criação do token.

```delphi
  THorse.Get('ping',
  procedure(Req: THorseRequest; Res: THorseResponse; Next: TProc)
  var
    LJWT: TJWT;
    LClaims: TMyClaims;
    LToken: String;
  begin
    LJWT := TJWT.Create(TMyClaims); // Add o claim personalizado

    LClaims := LJWT.Claims as TMyClaims; // Faz o TypeCast para atribuir na variavel

    LClaims.Expiration := IncHour(Now, 1);                   // Agora só alimentar
    LClaims.Id := '1';                                       //
    LClaims.Name := 'Danilo';                                // as informações
    LClaims.Email := 'developer.dlio@gmail.com';             //

    LToken := TJOSE.SHA256CompactToken('jwt-secret', LJWT);  // Gera o token

    FreeAndNil(LJWT);

    Res.Send(LToken);  // Envia o token
  end);
```

No exemplo abaixo podemos ver o TMyClaims sendo usado na leitura das informações do token.
```delphi
  THorse.Post('ping', HorseJWT('jwt-secret', TMyClaims), // NAO ESQUEÇA de add o Middleware que faz a verificação e passar o TMyClaims
    procedure(Req: THorseRequest; Res: THorseResponse; Next: TProc)
    var
      LClaims: TMyClaims;
    begin
      LClaims := Req.Session<TMyClaims>; // Pega a informação do Session e salva em uma variável com o tipo TMyClaims
      Res.Send(LClaims.Email);           // Faz a leitura, LClaims.Email - Lembrando que pode pegar outras informações do Claim também, como o expiration.
    end);
```

* Qualquer dúvida, podem me encontrar no Grupo do [Telegram](https://t.me/hashload)

**Comment by dliocode** [comment]
Só uma observação, caso não usem um Claim personalizado, a classe estará no Session é do tipo TJSONObject

**Comment by maicorheinheimer** [comment]
bom dia @dliocode perfeito só implementar os getters e setters para a classe, funcionou 100%.

**Comment by maicorheinheimer** [comment]
@dliocode seria interessante colocar esta parte do readme em custom session atualizar o exemplo da pagina inicial pelo menos com a implementação correta da classe TMyClaims.

**Comment by dliocode** [comment]
Será feito, até final de semana estará pronto..

**Comment by williammattos** [comment]
Acredito que já podemos fechar a issue, no pull #19 o amigo @dliocode já atualizou o README e descreve a forma de uso.
