### ISSUE TITLE
JWT Invalid token - FPC

### ISSUE THREAD

**Issue by laprado** [HashLoad/horse-jwt#35]
I'm getting an Unauthorized error message when trying to access an endpoint covered by Horse.Jwt. I noticed that on line 255 of Horse.Jwt.pas, it has an apparently invalid cast:
```pascal
try
      {$IF DEFINED(FPC)}
      LJSON := TJSONObject(LJWT.Claims.AsString); // line 255
```

When I change that line to use GetJson function:
```pascal
try
      {$IF DEFINED(FPC)}
      LJSON := TJSONObject(GetJson(LJWT.Claims.AsString)); // line 255
```

The problem no longer occurs and the middleware correctly validates the token.

I'm using this versions: 
FPC (3.2.2) 
Horse (3.0.2) 
Horse.Jwt (2.0.11).

I created a small program that reproduces the problem:

```pascal
program jsonCast;

{$MODE DELPHI}{$H+}

uses
  classes, sysutils, fpjson, jsonparser;

var
  jsonObj: TJSONObject;
  jsonText: string = '{"name":"John", "age":30}';
begin
  jsonObj := TJSONObject(jsonText); // raises an AV error. FPC doesn't warn about this invalid cast.
  //jsonObj := TJSONObject(GetJson(jsonText)); // use GetJson function to get a TJSONData that can be cast to TJSONObject.
  WriteLn(jsonObj.AsJSON);
  jsonObj.Free;
end.
```

If I'm wrong, let me know. Thanks.

**Comment by viniciussanchez** [comment]
@andre-djsystem consegue verificar isso? Você que tem mais experiência com o lazarus
