### ISSUE TITLE
Undeclared identifier: 'MatchRoute'

### ISSUE THREAD

**Issue by youngjara** [HashLoad/horse-jwt#38]
Hola buen día, no consigo compilar en Delphi 10.4, presenta el siguiente error:

[dcc64 Error] Horse.JWT.pas(177): E2003 Undeclared identifier: 'MatchRoute'

Gracias por la ayuda.

**Comment by CarlosHe** [comment]
El método MatchRoute está disponible en las versiones más recientes de Horse, actualice Horse.

**Comment by youngjara** [comment]
Entiendo, gracias por la respuesta.
